### ISSUE TITLE
client Build Error on android studio Arctic Fox 202.3.1 Patch 3

### ISSUE THREAD

**Issue by yamatakau08** [saccho/socket-sample#1]
I build client. The following error happens.
Could you support me.

```
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at org.jetbrains.kotlin.cli.jvm.plugins.ServiceLoaderLite.loadImplementations(ServiceLoaderLite.kt:51)
...
```

**Comment by yamatakau08** [comment]
Sorry I found the following info.
https://sun0range.com/information-technology/jaxb-exception/

If possible, could you update the source code to build success on latest android studio environment.

**Comment by saccho** [comment]
@yamatakau08 
Thank you for your feedback!
But now I haven't developed an Android app for years. So, I can't build this repository in my current environment and reproduce the bug, sorry.

I haven't tried it, but I think you can build this repository by choosing JDK1.8 (Java 8) in Android Studio.
https://stackoverflow.com/questions/67410927/java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-after-updating-to-a

If that doesn't solve the problem, you can fork this repository and fix it yourself.

Thank you.
